# Generated by Django 4.2.9 on 2024-03-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('api_url', models.URLField()),
                ('base64_authorization', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='is_staff',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
