# Generated by Django 4.2.9 on 2024-02-04 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrequest',
            name='is_accepted',
        ),
    ]
