# Generated by Django 4.2.9 on 2024-03-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='host_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
