# Generated by Django 4.2.9 on 2024-02-23 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_author_profile_image'),
        ('api', '0004_like_object_inbox'),
    ]

    operations = [
    ]
