# Generated by Django 4.2.9 on 2024-02-24 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20240223_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='followrequest',
            options={'ordering': ['-created_at']},
        ),
    ]
