# Generated by Django 5.0.2 on 2024-02-25 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20240223_2346'),
        ('api', '0006_alter_follower_options_alter_followrequest_options'),
    ]

    operations = [
    ]
