# Generated by Django 4.2.9 on 2024-02-25 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20240224_1847'),
        ('api', '0007_merge_20240224_1910'),
    ]

    operations = [
    ]
