# Generated by Django 4.2.9 on 2024-02-26 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20240224_2336'),
        ('api', '0008_merge_20240224_2053'),
    ]

    operations = [
    ]
