# Generated by Django 4.2.9 on 2024-03-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20240226_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sharedBy',
            field=models.CharField(default='', max_length=100),
        ),
    ]
