# Generated by Django 4.2.9 on 2024-03-16 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_post_sharedby'),
        ('api', '0012_post_image_url'),
    ]

    operations = [
    ]
