# Generated by Django 4.2.9 on 2024-03-18 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_post_image_post_image_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_base64',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
    ]
