# Generated by Django 4.2.9 on 2024-03-18 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_0010_post_sharedby_0012_post_image_url'),
        ('api', '0014_remove_post_image_base64_remove_post_image_url'),
    ]

    operations = [
    ]
